### PR TITLE
Bring up-to-date

### PR DESCRIPTION
**Pull request by nkk71**

### CODE REVIEW

**Comment by ItachiSan** [comment]
Is it possible to see this merged? Waiting for it from a long time ;)

**Comment by nkk71** [comment]
@ItachiSan this is outdated anyway, since android-7.1-mrom has been merged

**Comment by ItachiSan** [comment]
@nkk71 oh, where is it?
Maybe I can build it for my Nexus 5!

**Comment by nkk71** [comment]
Obsolete, deprecated.

**Pull request closed without merging**
