### PR TITLE
multirom: add support for 1440x2560

### PR DESCRIPTION
**Pull request by invisiblek**
Change-Id: I9828953c91bea328ebd53a081fb42580d9a721d7

### CODE REVIEW

**Comment by invisiblek** [comment]
tested working on LG G3

**Comment by Tasssadar** [comment]
Actually, this can't possibly work - it is missing all the MultiROM changes.

**Comment by invisiblek** [comment]
It definitely gave me the MultiROM menus. Before this clicking the MultROM button did nothing.

**Comment by Tasssadar** [comment]
Yes, some of them, but half the menus don't have their positions and changes to the header/templates also aren't there. Look at this diff to figure out the differences: https://www.diffchecker.com/5jysj47g (it is kinda hard to pinpoint which changes are from multirom and which from twrp, because the underlaying them has changed too - most of the number changes are from twrp, and most added things are from multirom).

**Pull request merged**
